### ISSUE TITLE
Burgers chapter

### ISSUE THREAD

**Issue by ketch** [clawpack/riemann_book#193]
I just went over the Burgers' equation chapter again and made many corrections (see https://github.com/clawpack/riemann_book/pull/192/commits/204d29ca41f4560771f29f4c82d6f4571ffa7491).  There were some issues I didn't solve:

1. The explanation in “Rarefaction wave” section doesn’t seem to make sense without talking about smoothing out the IC.  Since no initial point takes values between q_l and q_r, where do those values in the later solution come from?
2. In the section "Weak solutions":  I don't understand what is meant by saying "We can generalize this result."  What result?
3. In the same section: without saying more about the support of \phi, I don’t think the integration by parts makes sense.  Why do we get a boundary term at t=0 and not at the other boundaries?
4. What does “any form of the integral conservation law” mean?
5. The sentence starting “Note this rules out the interval…” doesn’t make sense to me.
6. Figure captions should say “x-t plane” rather than “xt-plane”.  But maybe it would be better to change them simply to “characteristics”.

Overall, the writing in this chapter feels to me like it assumes the reader already knows this material.  Is that the intent?

**Comment by maojrs** [comment]
Regarding the comments in Burgers'.

- The explanation in “Rarefaction wave” section doesn’t seem to make sense without talking about smoothing out the IC. Since no initial point takes values between q_l and q_r, where do those values in the later solution come from?
Not sure what you want to add here. Are you thinking of moving the self-similarity solution explanation in the Traffic_flow notebook into Burgers? We can do that.

-In the section "Weak solutions": I don't understand what is meant by saying "We can generalize this result." What result?
Minor wording, fixed.

In the same section: without saying more about the support of \phi, I don’t think the integration by parts makes sense. Why do we get a boundary term at t=0 and not at the other boundaries?
Compact support imples vanishing at infinity, so no problem here. Changed text to make that clear.

What does “any form of the integral conservation law” mean?
Minor wording, fixed.

The sentence starting “Note this rules out the interval…” doesn’t make sense to me.
Minor wording, fixed.

Figure captions should say “x-t plane” rather than “xt-plane”. But maybe it would be better to change them simply to “characteristics”.
Now they say characteristics.

I pushed a pulled request to more_editing_dk, with these minor changes.

**Comment by ketch** [comment]
Thanks, @maojrs.  Some comments:

>Not sure what you want to add here. Are you thinking of moving the self-similarity solution explanation in th
e Traffic_flow notebook into Burgers? We can do that.

I don't have a fix.  My preference would be to change the order back (Traffic chapter first); then this explanation is unneeded.

>Compact support imples vanishing at infinity, so no problem here. Changed text to make that clear.

It's still unclear why there is a boundary term at t=0.

>The sentence starting “Note this rules out the interval…” doesn’t make sense to me.
>Minor wording, fixed.

This still doesn't quite make sense to me (I know more or less what you're trying to say, but the sentence is unclear).

**Comment by maojrs** [comment]
>I don't have a fix. My preference would be to change the order back (Traffic chapter first); then this explanation is unneeded.

Well, then this is not about the Burgers' notebook, but about the order of the chapters. If we decide to keep the current order, then we need to decide if anything needs to be changed in Burgers' or if it is enough to introduce the basic concepts in Burgers' and leave more detailed explanations for later. I thought we chose the latter one, but we can talk again about it again. 

> It's still unclear why there is a boundary term at t=0.

More explanation added.

>This still doesn't quite make sense to me (I know more or less what you're trying to say, but the sentence is unclear).

Tried different wording. If it still doesn't quite makes sense to you, feel free to change it.

Latest changes should already be in the pull request.

**Comment by ketch** [comment]
@maojrs Remember that I was always opposed to changing the order of those chapters.  We spent a great deal of time polishing the traffic chapter to be the introduction to nonlinear conservation laws, while the Burgers chapter (which didn't exist at all in the original outline of the book) has undergone much less revision.  

When I reviewed the Burgers chapter I didn't bring this issue up.  But you suggested that the way to fix one of the problems with the Burgers chapter was to replace material in it with that of the Traffic chapter; if that's the case then it seems simpler (and,better) to just switch the chapters back.

**Comment by rjleveque** [comment]
Sorry if I complicated things moving the chapters around and then apparently not beefing up the Burgers' chapter enough.  I'll take another look at this today.  Regardless of order it might be good if both can somewhat stand on their own, since readers coming into the notebooks probably will not do them all in linear order.  Some will be attracted first to traffic flow while others might go straight to Burgers', particularly if they are using the notebooks to complement reading some text (or taking a class) where traffic flow isn't mentioned, and Burgers' is what they are trying to understand.

**Comment by maojrs** [comment]
Ok, then I will also make another pass to Burgers' to see if anything should be improved. I am also happy to incorporate any concrete suggestions/improvements both of you might have. 

@ketch Maybe we can merge the 'more_editing_dk' branch (including my latest pull request), so we do the changes in the latest version. However, there seems to be a problem with the Travis test.

**Comment by ketch** [comment]
Okay, I merged my PR.  The test failures are fixed in

https://github.com/rjleveque/riemann_book/pull/7

except for a lingering issue that I mentioned there and that I hope @rjleveque can tackle.

**Comment by maojrs** [comment]
Great, thanks!

**Comment by maojrs** [comment]
Issues addressed in pull request #194, so I am closing this one.
