### ISSUE TITLE
mpl_toolkits?

### ISSUE THREAD

**Issue by rjleveque** [clawpack/riemann_book#30]
The function `util/riemann_tools.plot_phase_3d` uses:
```
    from mpl_toolkits.mplot3d import Axes3D
```
This broke for a 574 student when trying to execute `Euler_approximate_solvers.ipynb`

`mpl_toolkits` apparently needs to be installed separately from `matplotlib`, although I think it is in the Anaconda distribution, for example.

**Comment by ketch** [comment]
Good point.  I don't know if the 3D plots are essential; what do you think?

For now I have created [a list of dependencies](https://github.com/clawpack/riemann_book/blob/master/README.md#dependencies) (all Python packages) in the README.  I'm not sure if it's complete.  We could also turn the book into a Python package and have a `requirements.txt` eventually.

**Comment by ketch** [comment]
After more searching, I believe that mpl_toolkits *is not* a separate package; it *is* included with matplotlib.  The most likely cause of this issue is an outdated matplotlib version.

Our requirements file now specifies that you need matplotlib version 2.0.0 or greater, and the instructions added to the readme in #34 will ensure that users get that, so I'm going to close this.
